version: '3'
services:
  sindri:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    volumes:
      - ./:/usr/local/src/custom_firmware/
    ulimits:
      nofile:
        soft: 64000
        hard: 64000
    environment:
      - QUILT_PATCHES=/usr/local/src/custom_firmware/conf/patches

