#!/bin/sh

# shellcheck disable=2018 disable=2019

# /etc/config/system
uci set system.@system[0].ttylogin=1
uci set system.@system[0].hostname="Openwrt-lhc"
uci set system.@system[0].log_size=1024
uci set system.@system[0].conloglevel='8'
uci set system.@system[0].cronloglevel='8'
uci commit system
/etc/init.d/system reload
sleep 2
logger -t "uci.default" "System config done"

# /etc/config/network
#uci set network.wan.metric='20'
#uci set network.wwan=interface
#uci set network.wwan.proto='dhcp'
uci set network.lan.ipaddr='10.10.0.1'


: <<'END'
# etc/config/dhcp
uci	del dhcp.lan.ra
uci	del dhcp.lan.ra_slaac
uci	del dhcp.lan.dhcpv6
uci	del dhcp.lan.ra_flags
uci	add_list dhcp.lan.ra_flags='none'
uci	uci add_list dhcp.lan.dhcp_option='6,8.8.8.8,8.8.4.4'

# /etc/config/wireless
uci set wireless.radio0.disabled='0'
uci set wireless.radio0.country='BR'
uci set wireless.radio0.channel='auto'
uci set wireless.radio0.txpower='25'
uci set wireless.radio0.cell_density='0'

uci set wireless.default_radio0.ssid="LHC-wrt"
uci set wireless.default_radio0.key="tijolo22"
uci set wireless.default_radio0.encryption="psk2"
uci set wireless.default_radio0.disabled='0
uci set wireless.default_radio0.disassoc_low_ack='0'


logger -t "uci.default" "Wireless config - ok"

END
uci commit
reload_config



[ -n "$FAILED" ] && exit 1

exit 0